### ISSUE TITLE
Rules returning only bool

### ISSUE THREAD

**Issue by tailhook** [hashicorp/sentinel-sdk#7]
After playing with the language a bit, I'm a bit confused about the limitations of the `rule` to return a boolean value.

I mean the language has a full model for math application and working with strings, lists, and dicts, but the whole calculation must converge to a boolean. I'd like to return integers and maybe other things in some sentinel files. So questions are:

1. Could the limitation be removed? I.e. the `rule` construct might be a predicate. But the return value of a sentinel (`main`) could be any type and typechecked only in context of where is it used?
2. Is it fine to allow more entry besides `main` ? I.e. use a `number_of_processes = 7` variable, or even calling a function `processes = func(num_servers) { num_servers * 2 }` ?

**Comment by mitchellh** [comment]
Hey sorry this took awhile to respond to.

The limitation of `rule` being a bool is to provide a meaningful constraint to the runtime and tracing. We also don't provide implicit "truthyness" type conversions since those become unclear (is `0` true or false? Well, it depends what language you're talking about). 

However, you can always assign intermediaries (as you said in 2) or you can use functions. 

`main` must always result in a boolean true or false because the result of a policy is `pass` or `fail` but that result can be gathered via non-boolean returning functions.
